# -*- coding: utf-8 -*-
"""WEC_Intel_SIG_PartB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1khTH0bpBciy0KZWORCzuMzC0keZs_OcO
"""

!pip install -U easynmt

!jupyter nbconvert --ClearMetadataPreprocessor.enabled=True --to notebook --inplace your_notebook.ipynb

"""**Experiment 1:** Using Opus-MT for Machine Translation

Creating an EasyNMT instance and loading a model. I am passing the model name I want to use and all needed files are downloaded and cached locally.
"""

pip install langid

from easynmt import EasyNMT
model = EasyNMT('opus-mt', language_detection_method='langid')

import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

sentences = ['In dieser Liste definieren wir mehrere Sätze.',
             'Jeder dieser Sätze wird dann in die Zielsprache übersetzt.',
             'Puede especificar en esta lista la oración en varios idiomas.',
             'El sistema detectará automáticamente el idioma y utilizará el modelo correcto.']
translations = model.translate(sentences, target_lang='en')

print("\n\nTranslations:")
for sent, trans in zip(sentences, translations):
  print(sent)
  print("=>", trans)
  print("")

"""**Document Translation**

I can also pass longer documents (or list of documents) to the translate() method.

As Transformer models can only translate inputs up to 512 (or 1024) word pieces, we first perform sentence splitting. Then, each sentence is translated individually.
"""

import tqdm
document = """Tokyo is the capital and most populous city of Japan, situated at the head of Tokyo Bay on the eastern coast of Honshu, the country’s largest island.
As of 2020, the Greater Tokyo Area had an estimated population of more than 37 million people, making it the most populous metropolitan region in the world.
Originally a small fishing village named Edo, the city became Japan’s political center in 1603 when Tokugawa Ieyasu established his shogunate there.
Edo was renamed Tokyo, meaning “Eastern Capital,” in 1868, when Emperor Meiji moved the imperial seat from Kyoto, marking the beginning of the Meiji Restoration and Japan’s rapid modernization.
Today, Tokyo is a major global financial and cultural hub, serving as the headquarters of many multinational corporations and international organizations.
The city blends cutting-edge technology with centuries-old tradition, where ancient temples stand beside futuristic skyscrapers and neon-lit shopping districts."""


print("Output:")
print(model.translate(document, target_lang='de'))

"""**Experiment 2**: Using mBART_50 for Machine Translation

"""

from easynmt import EasyNMT
model = EasyNMT('mbart50_m2m')

sentences = ['In dieser Liste definieren wir mehrere Sätze.',
             'Jeder dieser Sätze wird dann in die Zielsprache übersetzt.',
             'Puede especificar en esta lista la oración en varios idiomas.',
             'El sistema detectará automáticamente el idioma y utilizará el modelo correcto.']
translations = model.translate(sentences, target_lang='en')

print("\n\nTranslations:")
for sent, trans in zip(sentences, translations):
  print(sent)
  print("=>", trans)
  print("")

"""**Experiment 3**: Using M2M_100 for Machine Translation

"""

from easynmt import EasyNMT
model = EasyNMT('m2m_100_418M')

sentences = ['"इस सूची में, आप विभिन्न भाषाओं में वाक्य निर्दिष्ट कर सकते हैं।"']
translations = model.translate(sentences, target_lang='en')

print("\n\nTranslations:")
for sent, trans in zip(sentences, translations):
  print(sent)
  print("=>", trans)
  print("")

